---
title: "Re:Fresh E-Platform Usage"
output: html_document
---

```{r setup, include=FALSE}
Sys.setlocale(category = "LC_ALL", locale = "cht") # windows
knitr::opts_chunk$set(echo = TRUE)
library(formattable)
library(forcats)
library(magrittr)
library(dplyr)
library(highcharter) # highchart plot
library(googlesheets4)
library(knitr)
library(kableExtra)
library(xts)
library(tibble)
ss <- "1hTfspCDSNFCLp5qOlayq0wwr8gJfTVBbAyWsKaR7Ai8"
gs4_deauth()
participant_frequency_long <- read_sheet(ss, sheet = "participant_frequency_long")  %>% 
  mutate(eventName_r = case_when(eventName == "eventCount.frequency" ~ "人次", eventName == "eventCount.participant" ~ "人數"))
participant_frequency_wide <- read_sheet(ss, sheet = "participant_frequency_wide") 
colnames(participant_frequency_wide)[2] <- "人次"
colnames(participant_frequency_wide)[3] <- "人數"
colnames(participant_frequency_wide)[1] <- "日期"
xts_page_view <- read_sheet(ss, sheet = "page_view") %>% column_to_rownames(var = "date") %>% select(moving.average) %>% as.xts()
```

## Table

```{r table, echo=FALSE}
participant_frequency_wide %>% mutate('人次' = color_tile("transparent", "pink")(人次), '人數' = color_tile("transparent", "lightblue")(人數)) %>% kable("html", escape = F, full_width = T, align = "c") %>% kable_styling("hover", full_width = T)
```

## Plot

```{r plot, out.width='100%', echo=FALSE}
hchart(participant_frequency_long, "spline", hcaes(x = fct_reorder(factor(year.month), rowid), y = eventCount , group = eventName_r)) %>%
      hc_tooltip(
        crosshairs = TRUE,
        backgroundColor = "#F0F0F0",
        shared = TRUE, 
        borderWidth = 5
      ) %>% hc_xAxis(title = "") %>% hc_yAxis(title = "")
```


## Daily 人次

```{r daily plot, out.width='100%', echo=FALSE}
highchart(type = "stock") %>% 
  hc_add_series(xts_page_view, yAxis = 0, name = "人次")
```